--- #YAML:1.0
name:               Net-IPAddress-Util
version:            1.001
abstract:           Version-agnostic representation of an IP address
author:
    - Paul Bennett <paul.w.bennett@gmail.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Class::Std:    0.011
    Math::BigInt:  1.997
    Regexp::IPv6:  0.03
    Test::More:    0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
