---
abstract: 'Version-agnostic representation of an IP address'
author:
  - 'Paul Bennett <paul.w.bennett@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-IPAddress-Util
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  Class::Std: 0
  Exporter: 0
  List::MoreUtils: 0
  Test::More: 0
  mop: 0
  perl: 5.018000
version: 2.001_TRIAL
